import express from 'express';
import { editprofile, followOrUnfollow, getprofile, login, logout, register, suggestedusers } from '../controller/user.controller.js';
import isAuthenticated from '../middleware/isAuthenticated.js';
import upload from '../middleware/multer.js';
const router=express.Router();
router.route('/register').post(register);
router.route('/login').post(login);
router.route('/logout').get(logout);
router.route('/:id/profile').get(isAuthenticated,getprofile);
router.route('/profile/edit').post(isAuthenticated,upload.single('profilepic'),editprofile);
router.route('/suggestedUsers').get(isAuthenticated,suggestedusers);
router.route('/followOrUnfollow/:id').post(isAuthenticated,followOrUnfollow);
export default router;